name: Deploy on push

on:
  push:

jobs:
  pushing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get into right dir
        uses: cd type-quest

      - name: Setup npm
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run deployment script
        run: npm run deploy
        
