name: Deploy on push

on:
  push:

jobs:
  pushing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./type-quest
    steps:
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4.0.0
            

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup npm
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
        
